### ISSUE TITLE
building on debian vs. README

### ISSUE THREAD

**Issue by i-n-g-o** [cuspaceflight/tawhiri-downloader#2]
Hello.

In order to build the downloader on debian (buster) i needed to setup opam/ocaml in a slightly different way as stated in the README.

i needed to download opam 2.0.5 manually:
```bash
$ wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux
$ mv opam-2.0.5-x86_64-linux /usr/bin/opam
$ chmod a+x /usr/bin/opam
```

to init it i needed disable sandboxing:
```bash
$ opam init --comp=4.07.0 -y --disable-sandboxing
```

then i installed dune using opam:
```bash
$ opam install dune
```

using the pins on `cohttp.2.1.2` and `cohttp-async.2.1.2` failed and i compiled without the special versions.
not sure if pinning this version is still necessary?

i am very new to ocaml, so i did not try to use newer versions, some of this may be obsolete.

**Comment by danielrichman** [comment]
Fixed by c15704c .. dbc538c; readme updated
