### ISSUE TITLE
Question about the timezone should be used in tawhiri-downloader

### ISSUE THREAD

**Issue by luvwinnie** [cuspaceflight/tawhiri-downloader#3]
I'm using this tawhiri-downloader to try download the latest dataset.
In order to catch up getting latest dataset, which timezone should I set on the machine?

**Comment by danielrichman** [comment]
It does not depend on the timezone of the host machine, and should behave identically regardless. It uses UTC internally, ignoring the machine timezone.

**Comment by luvwinnie** [comment]
I have try with this however, it seems like it get slower than 6hours.
for example https://predict.habhub.org use 2022101100 at JST 2022 oct 11 12pm, meanwhile using this tawhiri-downloader it shows the download-2022101100 still downloading.
